version: '3.8'

services:
  db:
    image: mysql:latest  # Use mariadb:latest for MariaDB
    container_name: myblog_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myblog
      MYSQL_USER: mybloguser
      MYSQL_PASSWORD: myblogpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
